# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: their_coc
email: lbokeria@turing.ac.uk
full_name: Levan Bokeria
license: MIT
min_python_version: '3.10'
org: alan turing institute
project_name: heartfm-evals
project_short_description: A modular package for evaluating foundation model performance
    on various clinical tasks involving cardiac MRI and CT images.
python_name: heartfm_evals
typing: no_typing
url: https://github.com/alan-turing-institute/heartfm-evals
